'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=1.1.4322.2032.
'

'<remarks/>
<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="wsEmailSoap", [Namespace]:="http://tempuri.org/TKSIWebServer/wsEmail")>  _
Public Class wsEmail
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    '<remarks/>
    Public Sub New()
        MyBase.New
        Me.Url = "http://192.168.10.4/wsemail.asmx"
    End Sub
    
    '<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TKSIWebServer/wsEmail/GenericTester", RequestNamespace:="http://tempuri.org/TKSIWebServer/wsEmail", ResponseNamespace:="http://tempuri.org/TKSIWebServer/wsEmail", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function GenericTester(ByVal sTO As String, ByVal sCC As String, ByVal sSubject As String, ByVal sBody As String, ByVal sFrom As String) As String
        Dim results() As Object = Me.Invoke("GenericTester", New Object() {sTO, sCC, sSubject, sBody, sFrom})
        Return CType(results(0),String)
    End Function
    
    '<remarks/>
    Public Function BeginGenericTester(ByVal sTO As String, ByVal sCC As String, ByVal sSubject As String, ByVal sBody As String, ByVal sFrom As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("GenericTester", New Object() {sTO, sCC, sSubject, sBody, sFrom}, callback, asyncState)
    End Function
    
    '<remarks/>
    Public Function EndGenericTester(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),String)
    End Function
End Class
