'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=1.1.4322.2032.
'

'<remarks/>
<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="UpdateJobListSoap", [Namespace]:="http://tempuri.org/TKSIWEB/UpdateJobList")>  _
Public Class UpdateJobList
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    '<remarks/>
    Public Sub New()
        MyBase.New
        Me.Url = "http://installers.thekitchenshowcase.com/updatejoblist.asmx"
    End Sub
    
    '<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TKSIWEB/UpdateJobList/UploadJobs", RequestNamespace:="http://tempuri.org/TKSIWEB/UpdateJobList", ResponseNamespace:="http://tempuri.org/TKSIWEB/UpdateJobList", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function UploadJobs(ByVal xmlData As String) As String
        Dim results() As Object = Me.Invoke("UploadJobs", New Object() {xmlData})
        Return CType(results(0),String)
    End Function
    
    ''<remarks/>
    'Public Function BeginUploadJobs(ByVal xmlData As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
    '    Return Me.BeginInvoke("UploadJobs", New Object() {xmlData}, callback, asyncState)
    'End Function

    ''<remarks/>
    'Public Function EndUploadJobs(ByVal asyncResult As System.IAsyncResult) As String
    '    Dim results() As Object = Me.EndInvoke(asyncResult)
    '    Return CType(results(0),String)
    'End Function
    
    '<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TKSIWEB/UpdateJobList/GetLastWebSyncDate", RequestNamespace:="http://tempuri.org/TKSIWEB/UpdateJobList", ResponseNamespace:="http://tempuri.org/TKSIWEB/UpdateJobList", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function GetLastWebSyncDate() As String
        Dim results() As Object = Me.Invoke("GetLastWebSyncDate", New Object(-1) {})
        Return CType(results(0),String)
    End Function
    
    '<remarks/>
    Public Function BeginGetLastWebSyncDate(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("GetLastWebSyncDate", New Object(-1) {}, callback, asyncState)
    End Function
    
    '<remarks/>
    Public Function EndGetLastWebSyncDate(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),String)
    End Function
End Class
